version: '3.8'
services:
  rest-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rest-backend
    restart: always
    entrypoint: sh -c "npm install && npm run start:dev"
    environment:
      MONGODB_URI: ${MONGODB_URI}
    networks:
      - rest-network
    volumes:
      - .:/app/
      - /app/node_modules
    depends_on:
      - rest-mongodb
    links:
      - rest-mongodb
    ports:
      - ${PORT}:${PORT}

  rest-mongodb:
    image: mongo:latest
    container_name: rest_mongodb
    environment:
      MONGODB_URI: ${MONGODB_URI}
    volumes:
      - data-rest-mongodb:/data/db
    ports:
      - 27017:27017
    networks:
      - rest-network

volumes:
  data-rest-mongodb:

networks:
  rest-network:
